spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://39.102.58.201:3306/gulimall-oms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    alicloud:
      access-key: @hgzzLTAI4G2K6gKUYNfJ3nUyFGGo@hgzz
      secret-key: @hgzzFIE2OS4ZMZg7OFkYXmi7med6tIem49@hgzz
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  mapper-locations: classpath:/mapper/**/*.xml



server:
  port: 4000
