spring:
  cloud:
    gateway:
      routes:
#        - id: query_qq
#          uri: httsp://www.baidu.com
#          predicates:
#            - Query=url,qq
#
#        - id: query_baidu
#          uri: https://www.baidu.com
#          predicates:
#            - Query=url,baidu

        - id: route_member
          uri: lb://gulimall-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/(?<segment>/?.*),/$\{segment}

        - id: route_third_party
          uri: lb://gulimall-third-party
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/thirdparty/(?<segment>/?.*),/$\{segment}

        - id: route_product
          uri: lb://gulimall-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>/?.*),/$\{segment}

        - id: route_ware
          uri: lb://gulimall-ware
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>/?.*),/$\{segment}

        - id: route_admin
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>/?.*),/renren-fast/$\{segment}
#            - RewritePath=/api/(?<segment>/?.*), /renren-fast/$\{segment}
#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: test_route
#          uri: https://www.jd.com
#          predicates:
#            - Query=url,jd
#
#        - id: qq_route
#          uri: https://www.qq.com
#          predicates:
#            - Query=url,qq
#
#        - id: test_route1
#          uri: https://www.taobao.com
#          predicates:
#            - Query=url,taobao