spring:
  cloud:
    gateway:
      routes:
        - id: query_qq
          uri: httsp://www.baidu.com
          predicates:
            - Query=url,qq

        - id: query_baidu
          uri: https://www.baidu.com
          predicates:
            - Query=url,baidu
#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: test_route
#          uri: https://www.jd.com
#          predicates:
#            - Query=url,jd
#
#        - id: qq_route
#          uri: https://www.qq.com
#          predicates:
#            - Query=url,qq
#
#        - id: test_route1
#          uri: https://www.taobao.com
#          predicates:
#            - Query=url,taobao