spring:
  application:
    name: gulimall-third-party
  cloud:
    nacos:
      discovery:
        server-addr: 39.102.58.201:8848
    alicloud:
      access-key: LTAI4G2K6gKUYNfJ3nUyFGGo
      secret-key: FIE2OS4ZMZg7OFkYXmi7med6tIem49
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
        bucket: gulimall-hgzz

server:
  port: 30000
